version: "3.8"
services:
  shorturl:
    container_name: shorturl
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - mongo
    env_file:
      - ./.env
    networks:
      - webnet
    ports:
      - ${APP_PORT}:${APP_PORT}
  mongo_db:
    image: mongo
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - webnet
    depends_on:
      - nginx
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_INITDB_USERNAME=${DB_USER}
      - MONGO_INITDB_PASSWORD=${DB_PASS}
    env_file:
      - ./.env
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./db:/data/db
networks:
  webnet:
    driver: bridge