version: "3.8"
services:
  nginx:
      image: nginx:1.23.3-alpine
      container_name: nginx
      ports:
        - "80:80"
      networks:
        - webnet
      links:
        - shorturl
      volumes:
        - ./nginx/default.conf:/etc/nginx/nginx.conf

  shorturl:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - mongo
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_TYPE=${DB_TYPE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
    env_file:
      - ./.env
    networks:
      - webnet

  mongo_db:
    image: mongo
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - webnet
    depends_on:
      - nginx
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_INITDB_USERNAME=${DB_USER}
      - MONGO_INITDB_PASSWORD=${DB_PASS}
    env_file:
      - ./.env
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./db:/data/db
networks:
  webnet:
    driver: bridge